=== JoePelz/personal_site/joepolygon.com/assets/articles/blog.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT blog (section)+>

<!ELEMENT section (title, article+)>

<!ELEMENT article (path, image, title, style*, script*)>

<!ELEMENT path (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT script (#PCDATA)>

=== JoePelz/personal_site/joepolygon.com/assets/articles/articles.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE blog SYSTEM "blog.dtd">

<blog>
  <section>
    <title>Programming</title>
    <article>
      <title>Rix Compiler</title>
      <path>rix</path>
      <image>link.jpg</image>
      <style>/assets/articles/rix/rix.css</style>
    </article>
    <article>
      <title>Reversi AI</title>
      <path>reversi</path>
      <image>link.png</image>
    </article>
    <article>
      <title>Image Morpher</title>
      <path>imageMorpher</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Amoeba Platformer</title>
      <path>amoebaPlatformer</path>
      <image>link.jpg</image>
      <style>/assets/articles/amoebaPlatformer/amoeba.css</style>
    </article>
    <article>
      <title>Maze Generator</title>
      <path>mazeGenerator</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>PCM Encoder</title>
      <path>PCMEncoder</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Synthesizer Keyboard</title>
      <path>synthesizerKeyboard</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Circuitry</title>
      <path>circuitry</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Coding in Different Languages</title>
      <path>linguistics</path>
      <image>link.jpg</image>
      <script>/assets/js/collapse.js</script>
      <script>/assets/articles/linguistics/extra.js</script>
    </article>
    <article>
      <title>Generating Words and Language</title>
      <path>generatingLanguage</path>
      <image>link.png</image>
      <script>/assets/articles/generatingLanguage/letters.js</script>
      <script>/assets/articles/generatingLanguage/fragments.js</script>
      <script>/assets/articles/generatingLanguage/intrigue.js</script>
      <script>/assets/articles/generatingLanguage/latin.js</script>
    </article>
    <article>
      <title>Color Flip Puzzle</title>
      <path>colorFlip</path>
      <image>link.jpg</image>
      <script>/assets/articles/colorFlip/elm.js</script>
    </article>
  </section>
  <section>
    <title>School</title>
    <article>
      <title>Audio Processing</title>
      <path>audiomixer</path>
      <image>link.png</image>
    </article>
    <article>
      <title>Hamming Code</title>
      <path>hammingCode</path>
      <image>link.jpg</image>
      <script>/assets/articles/hammingCode/elm.js</script>
      <script>/assets/js/collapse.js</script>
    </article>
    <article>
      <title>IP Addresses</title>
      <path>ipAddress</path>
      <image>link.jpg</image>
      <script>/assets/articles/ipAddress/elm.js</script>
    </article>
    <article>
      <title>Venn Diagram Generator</title>
      <path>vennDiagram</path>
      <image>link.jpg</image>
      <style>/assets/articles/vennDiagram/table.css</style>
      <script>/assets/articles/vennDiagram/elm.js</script>
    </article>
    <article>
      <title>Binary Tree Builder</title>
      <path>binaryTree</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Edge Trigger, Flip Flop</title>
      <path>edgeTrigger</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Paint Program</title>
      <path>paint</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Making 2048</title>
      <path>2048</path>
      <image>link.jpg</image>
    </article>
  </section>
  <section>
    <title>Artistry</title>
    <article>
      <title>Kaleidoscope</title>
      <path>kaleidoscope</path>
      <image>link.jpg</image>
      <style>/assets/articles/kaleidoscope/kscope.css</style>
      <script>/assets/articles/kaleidoscope/kscope.js</script>
    </article>
    <article>
      <title>Carepal</title>
      <path>carepal</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>ICE Nodes</title>
      <path>iceNodes</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Nuke Expressions</title>
      <path>nukeExpressions</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>Demo Reel 2011</title>
      <path>reel11</path>
      <image>link.jpg</image>
    </article>
  </section>
  <section>
    <title>Inspiration</title>
    <article>
      <title>Inigo's Tutorials</title>
      <path>http://www.iquilezles.org/www/index.htm</path>
      <image>/assets/images/articles/InigoQuilez2.png</image>
    </article>
    <article>
      <title>This is Colossal</title>
      <path>http://www.thisiscolossal.com</path>
      <image>/assets/images/articles/thisIsColossal.jpg</image>
    </article>
    <article>
      <title>The Demoscene</title>
      <path>demoscene</path>
      <image>link.jpg</image>
    </article>
    <article>
      <title>.kkrieger</title>
      <path>http://www.pouet.net/prod.php?which=12036</path>
      <image>/assets/images/articles/kkreiger.jpg</image>
    </article>
    <article>
      <title>acko.net</title>
      <path>http://acko.net</path>
      <image>/assets/images/articles/ackonet.jpg</image>
    </article>
    <article>
      <title>Algorithm Visualization</title>
      <path>http://bost.ocks.org/mike/algorithms/</path>
      <image>/assets/images/articles/bostocksVisualizations.jpg</image>
    </article>
  </section>
</blog>
